-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-09-18 10:37:47 AEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo ON
SPOOL rcl_schema_output.txt

-- Group Name : G071
-- Group Members : OHQIHEN, Hirun


DROP TABLE author CASCADE CONSTRAINTS;

DROP TABLE author_catalogue_entry CASCADE CONSTRAINTS;

DROP TABLE book CASCADE CONSTRAINTS;

DROP TABLE bookstatus CASCADE CONSTRAINTS;

DROP TABLE borrower CASCADE CONSTRAINTS;

DROP TABLE borrowerclass CASCADE CONSTRAINTS;

DROP TABLE branch CASCADE CONSTRAINTS;

DROP TABLE catalogue CASCADE CONSTRAINTS;

DROP TABLE cataloguesubject CASCADE CONSTRAINTS;

DROP TABLE isbn CASCADE CONSTRAINTS;

DROP TABLE lga CASCADE CONSTRAINTS;

DROP TABLE loan CASCADE CONSTRAINTS;

DROP TABLE manager CASCADE CONSTRAINTS;

DROP TABLE publisher CASCADE CONSTRAINTS;

DROP TABLE reservation CASCADE CONSTRAINTS;

DROP TABLE subject CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE author (
    author_id        NUMBER(6) NOT NULL,
    author_firstname VARCHAR2(50),
    author_lastname  VARCHAR2(50)
);

COMMENT ON COLUMN author.author_id IS
    'Author id ';

COMMENT ON COLUMN author.author_firstname IS
    'Author first name ';

COMMENT ON COLUMN author.author_lastname IS
    'Author last name ';

ALTER TABLE author ADD CONSTRAINT author_pk PRIMARY KEY ( author_id );

CREATE TABLE author_catalogue_entry (
    catal_ddnco VARCHAR2(20) NOT NULL,
    author_id   NUMBER(6) NOT NULL
);

COMMENT ON COLUMN author_catalogue_entry.catal_ddnco IS
    'Dewey Decimal Call Number ';

COMMENT ON COLUMN author_catalogue_entry.author_id IS
    'Author id ';

ALTER TABLE author_catalogue_entry ADD CONSTRAINT author_catalogue_entry_pk PRIMARY KEY ( catal_ddnco,
                                                                                          author_id );

CREATE TABLE book (
    book_copyid           NUMBER(6) NOT NULL,
    branch_code           NUMBER(5) NOT NULL,
    book_purchasing_price NUMBER(6, 2) NOT NULL,
    bookstatus_id         NUMBER(2) NOT NULL,
    isbn_no               CHAR(13) NOT NULL
);

COMMENT ON COLUMN book.book_copyid IS
    'Book copy id ';

COMMENT ON COLUMN book.branch_code IS
    'Branch code';

COMMENT ON COLUMN book.book_purchasing_price IS
    'Book purchasing price ';

COMMENT ON COLUMN book.bookstatus_id IS
    'book status id ';

COMMENT ON COLUMN book.isbn_no IS
    '13-digit International Standard Book Numbers';

ALTER TABLE book ADD CONSTRAINT book_pk PRIMARY KEY ( book_copyid,
                                                      branch_code );

CREATE TABLE bookstatus (
    bookstatus_id   NUMBER(2) NOT NULL,
    bookstatus_name VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN bookstatus.bookstatus_id IS
    'book status id ';

COMMENT ON COLUMN bookstatus.bookstatus_name IS
    'Book Status Name ';

ALTER TABLE bookstatus ADD CONSTRAINT bookstatus_pk PRIMARY KEY ( bookstatus_id );

CREATE TABLE borrower (
    borrower_no                 NUMBER(6) NOT NULL,
    borrower_firstname          VARCHAR2(50),
    borrower_lastname           VARCHAR2(50),
    borrower_borrowing_status   CHAR(1) NOT NULL,
    borrower_contact_phoneno    CHAR(10),
    borrower_postcode           CHAR(4) NOT NULL,
    borrower_state              VARCHAR2(20) NOT NULL,
    borrower_street_number      VARCHAR2(5) NOT NULL,
    borrower_street_description VARCHAR2(100) NOT NULL,
    branch_code                 NUMBER(5) NOT NULL,
    borrowerclass_id            NUMBER(2) NOT NULL
);

ALTER TABLE borrower
    ADD CONSTRAINT chks_borrower_borrowing_status CHECK ( borrower_borrowing_status IN ( 'B', 'P' ) );

COMMENT ON COLUMN borrower.borrower_no IS
    'Borrower number ';

COMMENT ON COLUMN borrower.borrower_firstname IS
    'Borrower first name ';

COMMENT ON COLUMN borrower.borrower_lastname IS
    'Borrower last name ';

COMMENT ON COLUMN borrower.borrower_borrowing_status IS
    'Borrower_is_banned (T-TRUE, F-FALSE)';

COMMENT ON COLUMN borrower.borrower_contact_phoneno IS
    'Borrower contact phone number ';

COMMENT ON COLUMN borrower.borrower_postcode IS
    'Borrower postcode';

COMMENT ON COLUMN borrower.borrower_state IS
    'Borrower state ';

COMMENT ON COLUMN borrower.borrower_street_number IS
    'Borrower street number ';

COMMENT ON COLUMN borrower.borrower_street_description IS
    'Borrower street description';

COMMENT ON COLUMN borrower.branch_code IS
    'Branch code';

COMMENT ON COLUMN borrower.borrowerclass_id IS
    'Borrowerclass id ';

ALTER TABLE borrower ADD CONSTRAINT borrower_pk PRIMARY KEY ( borrower_no );

CREATE TABLE borrowerclass (
    borrowerclass_id            NUMBER(2) NOT NULL,
    borrowerclass_name          VARCHAR2(50) NOT NULL,
    borrowerclass_max_bookloans NUMBER(3) NOT NULL,
    borrowerclass_loanperiod    NUMBER(3) NOT NULL
);

COMMENT ON COLUMN borrowerclass.borrowerclass_id IS
    'Borrowerclass id ';

COMMENT ON COLUMN borrowerclass.borrowerclass_name IS
    'Borrowerclass name ';

COMMENT ON COLUMN borrowerclass.borrowerclass_max_bookloans IS
    'Borrowerclass maximum number of books loans ';

COMMENT ON COLUMN borrowerclass.borrowerclass_loanperiod IS
    'Borrower class loan period ';

ALTER TABLE borrowerclass ADD CONSTRAINT borrowerclass_pk PRIMARY KEY ( borrowerclass_id );

CREATE TABLE branch (
    branch_code            NUMBER(5) NOT NULL,
    branch_name            VARCHAR2(100) NOT NULL,
    branch_address         VARCHAR2(300) NOT NULL,
    branch_contact_phoneno CHAR(10) NOT NULL,
    lga_code               NUMBER(5) NOT NULL,
    manager_id             NUMBER(5) NOT NULL
);

COMMENT ON COLUMN branch.branch_code IS
    'Branch code';

COMMENT ON COLUMN branch.branch_name IS
    'Branch name';

COMMENT ON COLUMN branch.branch_address IS
    'Branch address ';

COMMENT ON COLUMN branch.branch_contact_phoneno IS
    'Branch contact phone number ';

COMMENT ON COLUMN branch.lga_code IS
    'LGA code';

COMMENT ON COLUMN branch.manager_id IS
    'Manager id ';

ALTER TABLE branch ADD CONSTRAINT branch_pk PRIMARY KEY ( branch_code );

CREATE TABLE catalogue (
    catal_ddnco            VARCHAR2(20) NOT NULL,
    catal_title            VARCHAR2(80) NOT NULL,
    catal_descrip          VARCHAR2(1000) NOT NULL,
    catal_publication_year DATE NOT NULL,
    catal_entry_cls        CHAR(1) NOT NULL,
    catal_page_count       NUMBER(5) NOT NULL,
    catal_language         VARCHAR2(20) NOT NULL,
    catal_reading_level    NUMBER(2),
    catal_note             VARCHAR2(60),
    catal_edition          NUMBER(3),
    publisher_id           NUMBER(6) NOT NULL
);

ALTER TABLE catalogue
    ADD CONSTRAINT chks_catal_entry_classific CHECK ( catal_entry_cls IN ( 'F', 'R' ) );

ALTER TABLE catalogue
    ADD CONSTRAINT chks_catal_readinglvl CHECK ( catal_reading_level BETWEEN 1 AND 30 );

COMMENT ON COLUMN catalogue.catal_ddnco IS
    'Dewey Decimal Call Number ';

COMMENT ON COLUMN catalogue.catal_title IS
    'Catalogue title ';

COMMENT ON COLUMN catalogue.catal_descrip IS
    'Catalogue description';

COMMENT ON COLUMN catalogue.catal_publication_year IS
    'Catalogue publication year';

COMMENT ON COLUMN catalogue.catal_entry_cls IS
    'Catalogue entry classification ';

COMMENT ON COLUMN catalogue.catal_page_count IS
    'Catalogue count of pages ';

COMMENT ON COLUMN catalogue.catal_language IS
    'Catalogue language ';

COMMENT ON COLUMN catalogue.catal_reading_level IS
    'Catalogue reading level';

COMMENT ON COLUMN catalogue.catal_note IS
    'Catalogue note ';

COMMENT ON COLUMN catalogue.catal_edition IS
    'Catalogue edition ';

COMMENT ON COLUMN catalogue.publisher_id IS
    'Publisher id ';

ALTER TABLE catalogue ADD CONSTRAINT catalogue_pk PRIMARY KEY ( catal_ddnco );

CREATE TABLE cataloguesubject (
    catal_ddnco VARCHAR2(20) NOT NULL,
    subject_id  CHAR(4) NOT NULL
);

COMMENT ON COLUMN cataloguesubject.catal_ddnco IS
    'Dewey Decimal Call Number ';

COMMENT ON COLUMN cataloguesubject.subject_id IS
    'Subject id ';

ALTER TABLE cataloguesubject ADD CONSTRAINT cataloguesubject_pk PRIMARY KEY ( catal_ddnco,
                                                                              subject_id );

CREATE TABLE isbn (
    isbn_no       CHAR(13) NOT NULL,
    isbn_booktype CHAR(2) NOT NULL,
    catal_ddnco   VARCHAR2(20) NOT NULL
);

ALTER TABLE isbn
    ADD CONSTRAINT chks_isbn_booktype CHECK ( isbn_booktype IN ( 'HC', 'LL', 'PB' ) );

COMMENT ON COLUMN isbn.isbn_no IS
    '13-digit International Standard Book Numbers';

COMMENT ON COLUMN isbn.isbn_booktype IS
    'Isbn book type ';

COMMENT ON COLUMN isbn.catal_ddnco IS
    'Dewey Decimal Call Number ';

ALTER TABLE isbn ADD CONSTRAINT isbn_pk PRIMARY KEY ( isbn_no );

ALTER TABLE isbn ADD CONSTRAINT catalogue_nk UNIQUE ( isbn_booktype,
                                                      catal_ddnco );

CREATE TABLE lga (
    lga_code                 NUMBER(5) NOT NULL,
    lga_name                 VARCHAR2(100) NOT NULL,
    lga_size                 NUMBER(7, 2) NOT NULL,
    lga_service_contact_name VARCHAR2(80) NOT NULL,
    lga_contact_phoneno      CHAR(10) NOT NULL
);

COMMENT ON COLUMN lga.lga_code IS
    'LGA code';

COMMENT ON COLUMN lga.lga_name IS
    'LGA''s name ';

COMMENT ON COLUMN lga.lga_size IS
    'LGA ''s size in hectares ';

COMMENT ON COLUMN lga.lga_service_contact_name IS
    'LGA Service Contact''s name ';

COMMENT ON COLUMN lga.lga_contact_phoneno IS
    'LGA''s contact phone number ';

ALTER TABLE lga ADD CONSTRAINT lga_pk PRIMARY KEY ( lga_code );

CREATE TABLE loan (
    loan_id                     NUMBER(7) NOT NULL,
    loan_start_datetime         DATE NOT NULL,
    loan_due_date               DATE NOT NULL,
    loan_return_date__and__time DATE,
    loan_fine_amount            NUMBER(3),
    loan_date_finepaid          DATE,
    book_copyid                 NUMBER(6) NOT NULL,
    branch_code                 NUMBER(5) NOT NULL,
    borrower_no                 NUMBER(6) NOT NULL
);

COMMENT ON COLUMN loan.loan_id IS
    'Loan id ';

COMMENT ON COLUMN loan.loan_start_datetime IS
    'Loan start date time ';

COMMENT ON COLUMN loan.loan_due_date IS
    'Loan due date ';

COMMENT ON COLUMN loan.loan_return_date__and__time IS
    'Loan return date  and time ';

COMMENT ON COLUMN loan.loan_fine_amount IS
    'Loan fine amount ';

COMMENT ON COLUMN loan.loan_date_finepaid IS
    'Loan date fine paid ';

COMMENT ON COLUMN loan.book_copyid IS
    'Book copy id ';

COMMENT ON COLUMN loan.branch_code IS
    'Branch code';

COMMENT ON COLUMN loan.borrower_no IS
    'Borrower number ';

ALTER TABLE loan ADD CONSTRAINT loan_pk PRIMARY KEY ( loan_id );

ALTER TABLE loan
    ADD CONSTRAINT loan_nk UNIQUE ( loan_start_datetime,
                                    book_copyid,
                                    branch_code );

CREATE TABLE manager (
    manager_id              NUMBER(5) NOT NULL,
    manager_firstname       VARCHAR2(30),
    manager_lastname        VARCHAR2(30),
    manager_contact_phoneno CHAR(10) NOT NULL,
    branch_code             NUMBER(5) NOT NULL
);

COMMENT ON COLUMN manager.manager_id IS
    'Manager id ';

COMMENT ON COLUMN manager.manager_firstname IS
    'Manager first name ';

COMMENT ON COLUMN manager.manager_lastname IS
    'lManager last name ';

COMMENT ON COLUMN manager.manager_contact_phoneno IS
    'Manager contact phone number ';

COMMENT ON COLUMN manager.branch_code IS
    'Branch code';

CREATE UNIQUE INDEX manager__idx ON
    manager (
        branch_code
    ASC );

ALTER TABLE manager ADD CONSTRAINT manager_pk PRIMARY KEY ( manager_id );

CREATE TABLE publisher (
    publisher_id   NUMBER(6) NOT NULL,
    publisher_name VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN publisher.publisher_id IS
    'Publisher id ';

COMMENT ON COLUMN publisher.publisher_name IS
    'Publisher name ';

ALTER TABLE publisher ADD CONSTRAINT publisher_pk PRIMARY KEY ( publisher_id );

CREATE TABLE reservation (
    reservation_id        NUMBER(7) NOT NULL,
    reservation_date_time DATE NOT NULL,
    book_copyid           NUMBER(6) NOT NULL,
    branch_code           NUMBER(5) NOT NULL,
    borrower_no           NUMBER(6) NOT NULL
);

COMMENT ON COLUMN reservation.reservation_id IS
    'Reservation id ';

COMMENT ON COLUMN reservation.reservation_date_time IS
    'Reservation date and time ';

COMMENT ON COLUMN reservation.book_copyid IS
    'Book copy id ';

COMMENT ON COLUMN reservation.branch_code IS
    'Branch code';

COMMENT ON COLUMN reservation.borrower_no IS
    'Borrower number ';

ALTER TABLE reservation ADD CONSTRAINT reservation_pk PRIMARY KEY ( reservation_id );

ALTER TABLE reservation
    ADD CONSTRAINT reservation_uq UNIQUE ( book_copyid,
                                           branch_code,
                                           borrower_no );

CREATE TABLE subject (
    subject_id          CHAR(4) NOT NULL,
    subject_description VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN subject.subject_id IS
    'Subject id ';

COMMENT ON COLUMN subject.subject_description IS
    'Subject description';

ALTER TABLE subject ADD CONSTRAINT subject_pk PRIMARY KEY ( subject_id );

ALTER TABLE author_catalogue_entry
    ADD CONSTRAINT author_author_catal_fk FOREIGN KEY ( author_id )
        REFERENCES author ( author_id );

ALTER TABLE loan
    ADD CONSTRAINT book_loan_fk FOREIGN KEY ( book_copyid,
                                              branch_code )
        REFERENCES book ( book_copyid,
                          branch_code );

ALTER TABLE reservation
    ADD CONSTRAINT book_reservation_fk FOREIGN KEY ( book_copyid,
                                                     branch_code )
        REFERENCES book ( book_copyid,
                          branch_code );

ALTER TABLE book
    ADD CONSTRAINT bookstatus_book_fk FOREIGN KEY ( bookstatus_id )
        REFERENCES bookstatus ( bookstatus_id );

ALTER TABLE borrower
    ADD CONSTRAINT borrower_branch_fk FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE loan
    ADD CONSTRAINT borrower_loan_fk FOREIGN KEY ( borrower_no )
        REFERENCES borrower ( borrower_no );

ALTER TABLE reservation
    ADD CONSTRAINT borrower_reservation_fk FOREIGN KEY ( borrower_no )
        REFERENCES borrower ( borrower_no );

ALTER TABLE borrower
    ADD CONSTRAINT borrowerclass_borrower_fk FOREIGN KEY ( borrowerclass_id )
        REFERENCES borrowerclass ( borrowerclass_id );

ALTER TABLE book
    ADD CONSTRAINT branch_book_fk FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE manager
    ADD CONSTRAINT branch_manager_fk FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE author_catalogue_entry
    ADD CONSTRAINT catal_author_catalogue_fk FOREIGN KEY ( catal_ddnco )
        REFERENCES catalogue ( catal_ddnco );

ALTER TABLE cataloguesubject
    ADD CONSTRAINT catalogue_cataloguesubject_fk FOREIGN KEY ( catal_ddnco )
        REFERENCES catalogue ( catal_ddnco );

ALTER TABLE isbn
    ADD CONSTRAINT catalogue_isbn_fk FOREIGN KEY ( catal_ddnco )
        REFERENCES catalogue ( catal_ddnco );

ALTER TABLE book
    ADD CONSTRAINT isbn_book_fk FOREIGN KEY ( isbn_no )
        REFERENCES isbn ( isbn_no );

ALTER TABLE branch
    ADD CONSTRAINT lga_branch_fk FOREIGN KEY ( lga_code )
        REFERENCES lga ( lga_code );

ALTER TABLE branch
    ADD CONSTRAINT manager_branch_fk FOREIGN KEY ( manager_id )
        REFERENCES manager ( manager_id );

ALTER TABLE catalogue
    ADD CONSTRAINT publisher_catalogue_fk FOREIGN KEY ( publisher_id )
        REFERENCES publisher ( publisher_id );

ALTER TABLE cataloguesubject
    ADD CONSTRAINT subject_cataloguesubject_fk FOREIGN KEY ( subject_id )
        REFERENCES subject ( subject_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             1
-- ALTER TABLE                             41
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
set echo off 
SPOOL off